# Generated by Django 3.2.12 on 2023-10-20 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_students'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
            ],
        ),
    ]
