# Generated by Django 3.2.12 on 2023-11-04 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_tickerdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickerdata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tickerdata',
            name='closing_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tickerdata',
            name='opening_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
