# Generated by Django 3.2.12 on 2023-11-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_auto_20231104_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickerdata',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
